In [1]:
import numpy as np
import torch 
from torch.utils.data import DataLoader,TensorDataset

In [2]:
nobservations=100
nFeatures=20

data=np.random.randn(nobservations,nFeatures)

dataT=torch.tensor(data)

In [5]:
print('Numpy data:')

print(type(data))
print(data.shape)
print(data.dtype)
print(' ')
print('Tensor data:')
print(type(dataT))
print(dataT.size())
print(dataT.dtype)

Numpy data:
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data:
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64


In [6]:
dataT2=torch.tensor(data).float()
print(dataT2.dtype)

dataT3=torch.tensor(data).long()
print(dataT3.dtype)

torch.float32
torch.int64


In [7]:
dataset=TensorDataset(dataT)
dataset.tensors

(tensor([[ 1.0623, -1.3798, -1.2111,  ..., -1.3917, -2.1193,  1.0562],
         [-0.8444, -1.4110,  0.2617,  ...,  0.0765,  1.6280,  0.8736],
         [ 0.1611, -0.4820, -0.9538,  ...,  0.5259,  1.2266,  0.4278],
         ...,
         [-1.0125, -0.3172,  1.8227,  ..., -0.4792, -0.2111, -0.2987],
         [-1.0075,  0.5531, -0.9283,  ..., -0.7503,  0.1109,  1.1198],
         [-0.8501,  1.8587,  0.2029,  ...,  0.1266, -1.9430,  0.8669]],
        dtype=torch.float64),)

In [8]:
labels=torch.ceil(torch.linspace(.01,4,nobservations))

labels=labels.reshape((len(labels),1))
print(labels)

dataset=TensorDataset(dataT,labels)
print(dataset.tensors[0].size())
print(dataset.tensors[1].size())

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
      

### DataLoader

In [9]:
batchsize=25
dataloader=DataLoader(dataset,batch_size=batchsize)
dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [11]:
for dat,labs in dataloader:
    print('BAtch info:')
    print(dat.size())
    print(labs.size())
    print(' ')

BAtch info:
torch.Size([25, 20])
torch.Size([25, 1])
 
BAtch info:
torch.Size([25, 20])
torch.Size([25, 1])
 
BAtch info:
torch.Size([25, 20])
torch.Size([25, 1])
 
BAtch info:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [13]:
for dat,labs in dataloader:
    print(data.T)
    print(' ')

[[ 1.06232696 -0.84442346  0.16106739 ... -1.01248797 -1.00746612
  -0.85008285]
 [-1.37981872 -1.41099809 -0.4820109  ... -0.3171944   0.55306874
   1.8587221 ]
 [-1.21107442  0.26168817 -0.95381569 ...  1.82272474 -0.92825644
   0.20291866]
 ...
 [-1.39169024  0.07647434  0.52591079 ... -0.47923268 -0.75028725
   0.12656064]
 [-2.11928941  1.62802811  1.22657    ... -0.21112905  0.11089904
  -1.94301235]
 [ 1.0562302   0.87361133  0.42783003 ... -0.29870186  1.11984896
   0.86691573]]
 
[[ 1.06232696 -0.84442346  0.16106739 ... -1.01248797 -1.00746612
  -0.85008285]
 [-1.37981872 -1.41099809 -0.4820109  ... -0.3171944   0.55306874
   1.8587221 ]
 [-1.21107442  0.26168817 -0.95381569 ...  1.82272474 -0.92825644
   0.20291866]
 ...
 [-1.39169024  0.07647434  0.52591079 ... -0.47923268 -0.75028725
   0.12656064]
 [-2.11928941  1.62802811  1.22657    ... -0.21112905  0.11089904
  -1.94301235]
 [ 1.0562302   0.87361133  0.42783003 ... -0.29870186  1.11984896
   0.86691573]]
 
[[ 1.0623269

In [15]:
dat,labs=next(iter(dataloader))
print(labs)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
