In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


### Using Dropout

In [6]:
prob=0.25
dropout=nn.Dropout(p=prob)
x=torch.ones(10)
## dropout returns 
y=dropout(x)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 0., 1., 1., 0., 1., 0., 0., 1., 1.])
tensor(0.8000)


In [5]:
dropout.eval()
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [7]:
dropout.eval()
y=F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 0., 2., 0., 0., 0., 2., 2., 2., 0.])
tensor(1.)


In [8]:
dropout.eval()
y=F.dropout(x,training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [11]:
dropout.train()
y=dropout(x)
print(y)
print(' ')

dropout.eval()
y=dropout(x)
print(y)
print(' ')
y=dropout(x)
print(torch.mean(y))

tensor([1.3333, 1.3333, 1.3333, 1.3333, 1.3333, 0.0000, 1.3333, 1.3333, 0.0000,
        1.3333])
 
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 
tensor(1.)
