In [20]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

In [21]:
import seaborn as sns
import torch

# ডেটাসেট লোড
iris = sns.load_dataset('iris')

# ইনপুট ফিচারগুলোকে টেনসরে রূপান্তর
data = torch.tensor(iris[iris.columns[0:4]].values).float()  # 🔸 .float() ব্যবহার করো dtype মিলাতে

# লেবেল ইনিশিয়ালাইজ
labels = torch.zeros(len(data), dtype=torch.long)

# 🔸 spelling mistake ফিক্স করা হয়েছে: 'verginica' → 'virginica'
labels[iris.species == 'versicolor'] = 1
labels[iris.species == 'virginica'] = 2


In [22]:
fakedata=np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels=np.arange(10)>4
print(fakedata),print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


In [23]:
fakedataldr=DataLoader(fakedata,shuffle=True)
print(fakedataldr)
print(fakedataldr.batch_size)

1


In [24]:
for i,oneSample in enumerate(fakedataldr):
    print(i,oneSample,oneSample.shape)

0 tensor([[61, 62, 63, 64]]) torch.Size([1, 4])
1 tensor([[71, 72, 73, 74]]) torch.Size([1, 4])
2 tensor([[51, 52, 53, 54]]) torch.Size([1, 4])
3 tensor([[21, 22, 23, 24]]) torch.Size([1, 4])
4 tensor([[41, 42, 43, 44]]) torch.Size([1, 4])
5 tensor([[81, 82, 83, 84]]) torch.Size([1, 4])
6 tensor([[91, 92, 93, 94]]) torch.Size([1, 4])
7 tensor([[101, 102, 103, 104]]) torch.Size([1, 4])
8 tensor([[11, 12, 13, 14]]) torch.Size([1, 4])
9 tensor([[31, 32, 33, 34]]) torch.Size([1, 4])


In [25]:
fakedataset=torch.utils.data.TensorDataset(torch.Tensor(fakedata),torch.Tensor(fakelabels))
print(fakedataset.tensors),print(' ')
fakedataLdr=DataLoader(fakedataset,shuffle=True)

for dat,lab in fakedataLdr:
    print(dat,lab)

(tensor([[ 11.,  12.,  13.,  14.],
        [ 21.,  22.,  23.,  24.],
        [ 31.,  32.,  33.,  34.],
        [ 41.,  42.,  43.,  44.],
        [ 51.,  52.,  53.,  54.],
        [ 61.,  62.,  63.,  64.],
        [ 71.,  72.,  73.,  74.],
        [ 81.,  82.,  83.,  84.],
        [ 91.,  92.,  93.,  94.],
        [101., 102., 103., 104.]]), tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]))
 
tensor([[91., 92., 93., 94.]]) tensor([1.])
tensor([[71., 72., 73., 74.]]) tensor([1.])
tensor([[11., 12., 13., 14.]]) tensor([0.])
tensor([[51., 52., 53., 54.]]) tensor([0.])
tensor([[61., 62., 63., 64.]]) tensor([1.])
tensor([[31., 32., 33., 34.]]) tensor([0.])
tensor([[81., 82., 83., 84.]]) tensor([1.])
tensor([[21., 22., 23., 24.]]) tensor([0.])
tensor([[41., 42., 43., 44.]]) tensor([0.])
tensor([[101., 102., 103., 104.]]) tensor([1.])


In [26]:
train_data,test_data,train_labels,test_labels=train_test_split(fakedata,fakelabels,test_size=.2)

train_data=torch.utils.data.TensorDataset(
    torch.Tensor(train_data),torch.Tensor(train_labels)
)

test_data=torch.utils.data.TensorDataset(
    torch.Tensor(test_data),torch.Tensor(test_labels)
)

train_loader=DataLoader(train_data,batch_size=4)
test_loader=DataLoader(test_data)

In [27]:
print('Training Data')
for batch,label in train_loader:
    print(batch,label)
    print(' ')

print('Testing Data')
for batch,label in test_loader:
    print(batch,label)
    print(' ')

Training Data
tensor([[41., 42., 43., 44.],
        [11., 12., 13., 14.],
        [91., 92., 93., 94.],
        [61., 62., 63., 64.]]) tensor([0., 0., 1., 1.])
 
tensor([[71., 72., 73., 74.],
        [31., 32., 33., 34.],
        [81., 82., 83., 84.],
        [21., 22., 23., 24.]]) tensor([1., 0., 1., 0.])
 
Testing Data
tensor([[51., 52., 53., 54.]]) tensor([0.])
 
tensor([[101., 102., 103., 104.]]) tensor([1.])
 


In [28]:
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

# ডেটা split করা
train_data, test_data, train_labels, test_labels = train_test_split(data, labels, test_size=0.8)

#  TensorDataset তৈরি (সঠিকভাবে)
train_data = TensorDataset(train_data, train_labels)
test_data = TensorDataset(test_data, test_labels)

# DataLoader তৈরি
train_loader = DataLoader(train_data, shuffle=True, batch_size=12)
test_loader = DataLoader(test_data, batch_size=test_data.tensors[0].shape[0])


In [29]:
for X,y in train_loader:
    print(X.shape,y.shape)

X,y


torch.Size([12, 4]) torch.Size([12])
torch.Size([12, 4]) torch.Size([12])
torch.Size([6, 4]) torch.Size([6])


(tensor([[6.3000, 2.3000, 4.4000, 1.3000],
         [7.1000, 3.0000, 5.9000, 2.1000],
         [5.4000, 3.7000, 1.5000, 0.2000],
         [6.3000, 2.5000, 4.9000, 1.5000],
         [6.7000, 3.3000, 5.7000, 2.1000],
         [4.6000, 3.2000, 1.4000, 0.2000]]),
 tensor([1, 2, 0, 1, 2, 0]))

In [40]:
import torch
import torch.nn as nn

def createANewModel():
    # 🔹 Model Architecture
    ANNiris = nn.Sequential(
        nn.Linear(4, 64),
        nn.ReLU(),
        nn.Linear(64, 64),
        nn.ReLU(),
        nn.Linear(64, 3),  # 3 classes for Iris dataset
    )
    model = createANewModel(dropoutRate=0.25)


    # 🔹 Loss Function (multi-class classification)
    lossfun = nn.CrossEntropyLoss()

    # 🔹 Optimizer
    optimizer = torch.optim.SGD(ANNiris.parameters(), lr=0.01)

    return ANNiris, lossfun, optimizer


In [45]:
def trainTheModel(model, lossfun, optimizer, train_loader, test_loader, numepochs=100):
    trainAcc = []
    testAcc = []

    for epochi in range(numepochs):
        batchAcc = []

        # 🔹 Training mode
        model.train()
        for X, y in train_loader:
            yHat = model(X)
            loss = lossfun(yHat, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Accuracy calculation
            preds = torch.argmax(yHat, axis=1)
            acc = 100 * torch.mean((preds == y).float()).item()
            batchAcc.append(acc)

        trainAcc.append(np.mean(batchAcc))

        # 🔹 Evaluation mode
        model.eval()
        with torch.no_grad():
            batchTestAcc = []
            for Xtest, ytest in test_loader:
                yPred = model(Xtest)
                predsTest = torch.argmax(yPred, axis=1)
                accTest = 100 * torch.mean((predsTest == ytest).float()).item()
                batchTestAcc.append(accTest)

            testAcc.append(np.mean(batchTestAcc))  # গড় নিয়ে সংরক্ষণ করা হচ্ছে

    return trainAcc, testAcc
