In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# Create a random image (1 channel, 1 image of size 6x6)
img = torch.tensor([[[[1, 2, 3, 4, 5, 6],
                      [6, 5, 4, 3, 2, 1],
                      [1, 3, 5, 7, 5, 3],
                      [2, 4, 6, 8, 6, 4],
                      [9, 8, 7, 6, 5, 4],
                      [3, 1, 2, 4, 6, 8]]]], dtype=torch.float32)

# Define max pooling
maxpool = nn.MaxPool2d(kernel_size=2, stride=2)

# Apply max pooling
max_pooled = maxpool(img)

# Min pooling by negating the input and then negating the result
min_pooled = -maxpool(-img)

# Print the results
print("Original Image:\n", img[0,0])
print("\nMax Pooled:\n", max_pooled[0,0])
print("\nMin Pooled:\n", min_pooled[0,0])


Original Image:
 tensor([[1., 2., 3., 4., 5., 6.],
        [6., 5., 4., 3., 2., 1.],
        [1., 3., 5., 7., 5., 3.],
        [2., 4., 6., 8., 6., 4.],
        [9., 8., 7., 6., 5., 4.],
        [3., 1., 2., 4., 6., 8.]])

Max Pooled:
 tensor([[6., 4., 6.],
        [4., 8., 6.],
        [9., 7., 8.]])

Min Pooled:
 tensor([[1., 3., 1.],
        [1., 5., 3.],
        [1., 2., 4.]])
